sudo: false
language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.0

gemfile:
  - gemfiles/fluentd_0.10.gemfile
  - gemfiles/fluentd_0.12.gemfile

before_script: gem update bundler
script: bundle exec rake test
